remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: [BD-1 Back Panel Build]
description: [How to build BD-1 back panel.]

